spring:
  cloud:
    gateway:
      discovery:
        locator:
          # Enables service discovery integration
          # Allows automatic route creation based on service IDs in discovery server
          enabled: true
      routes:
        # Customer service route configuration
        - id: customer-service
          # 'lb:' prefix enables client-side load balancing through Eureka
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            # Routes requests matching this path pattern to the customer service
            - Path=/api/v1/customers/**

        # Order service route configuration
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**

        # Order lines endpoint (also routed to the order service)
        - id: order-lines-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**

        # Payment service route configuration
        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

server:
  # Port for the API gateway
  port: 8222