# config-server.application.yml
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          # Defines the location where our configuration files are stored
          search-locations: classpath:/configurations

server:
  port: 8888